# Generated by Django 5.0.4 on 2026-05-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('issue_type', models.CharField(choices=[('MISSING', 'MISSING'), ('INVALID', 'INVALID'), ('INVALID_VALUE', 'INVALID_VALUE'), ('INVALID_TYPE', 'INVALID_TYPE')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawupload')),
            ],
        ),
    ]
