# Generated by Django 5.0.4 on 2026-05-30 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auditlog_normalizedrecord_activity_type_and_more'),
        ('reviews', '0003_alter_dataissue_id_alter_recordreview_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordreview',
            name='record_id',
        ),
        migrations.AddField(
            model_name='dataissue',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataissue',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='records.normalizedrecord'),
        ),
        migrations.AddField(
            model_name='dataissue',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataissue',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recordreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordreview',
            name='decision_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordreview',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='records.normalizedrecord'),
        ),
        migrations.AddField(
            model_name='recordreview',
            name='review_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recordreview',
            name='reviewer_name',
            field=models.CharField(default='Analyst', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataissue',
            name='issue_type',
            field=models.CharField(choices=[('MISSING', 'MISSING'), ('INVALID', 'INVALID'), ('INVALID_VALUE', 'INVALID_VALUE'), ('INVALID_TYPE', 'INVALID_TYPE'), ('SUSPICIOUS', 'SUSPICIOUS')], max_length=50),
        ),
    ]
