# Generated by Django 5.0.4 on 2026-05-30 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('raw_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='ingestion.rawupload')),
            ],
        ),
    ]
