# Generated by Django 5.0.4 on 2026-05-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('source_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='UPLOADED', max_length=20)),
            ],
        ),
    ]
