# Generated by Django 5.0.4 on 2026-05-29 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=20)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('cost_inr', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawupload')),
            ],
            options={
                'indexes': [models.Index(fields=['source_type'], name='records_nor_source__a76458_idx'), models.Index(fields=['status'], name='records_nor_status_b5fcae_idx')],
            },
        ),
    ]
