# Generated by Django 6.0.5 on 2026-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='normalizedrecord',
            name='records_nor_source__a76458_idx',
        ),
        migrations.RemoveIndex(
            model_name='normalizedrecord',
            name='records_nor_status_b5fcae_idx',
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='source_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='status',
            field=models.CharField(choices=[('VALID', 'VALID'), ('INVALID', 'INVALID')], default='VALID', max_length=20),
        ),
    ]
