# Generated by Django 5.0.4 on 2026-05-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_normalizedrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
