# Generated by Django 6.0.5 on 2026-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_normalizedrecord_records_nor_source__a76458_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
