# Generated by Django 5.0.4 on 2026-05-30 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('records', '0003_alter_normalizedrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedrecord',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='raw_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.rawupload'),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('VALID', 'VALID'), ('INVALID', 'INVALID'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
    ]
