# Generated by Django 5.0.4 on 2026-05-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('records', '0004_alter_normalizedrecord_raw_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD', 'UPLOAD'), ('NORMALIZED', 'NORMALIZED'), ('ISSUE_CREATED', 'ISSUE_CREATED'), ('REVIEWED', 'REVIEWED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('LOCKED', 'LOCKED')], max_length=50)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='billing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='billing_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='facility_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='locked_for_audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='normalized_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='plant_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='scope_category',
            field=models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], default='SCOPE_1', max_length=20),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='source_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='source_record_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='source_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='tenant_id',
            field=models.CharField(default='default_tenant', max_length=100),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('VALID', 'VALID'), ('INVALID', 'INVALID'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('LOCKED', 'LOCKED')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['scope_category'], name='records_nor_scope_c_6978d0_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='records.normalizedrecord'),
        ),
    ]
